//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Trainings = new HashSet<Training>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Duration { get; set; }
        public string Fee { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Training> Trainings { get; set; }
    }
}
